# Generated by Django 3.2 on 2023-05-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230519_2037'),
        ('reviews', '0006_auto_20230520_1858'),
    ]

    operations = [
    ]
